module.exports = {
  data: [
    { code: '15101', name: '1º Juzgado de Letras de Arica' },
    { code: '15101', name: '1º Juzgado De Letras de Arica ex 4°' },
    { code: '15101', name: '2º Juzgado de Letras de Arica' },
    { code: '15101', name: '2º Juzgado De Letras de Arica ex 4°' },
    { code: '15101', name: '3º Juzgado de Letras de Arica Ex 4º' },
    { code: '15101', name: '3º Juzgado de Letras de Arica' },
    { code: '01401', name: 'Juzgado de Letras y Gar. Pozo Almonte' },
    { code: '01101', name: '1º Juzgado de Letras de Iquique' },
    { code: '01101', name: '2º Juzgado de Letras de Iquique' },
    { code: '01101', name: '3º Juzgado de Letras de Iquique' },
    { code: '02301', name: 'Juzgado de Letras Tocopilla' },
    { code: '02201', name: '1º Juzgado de Letras de Calama' },
    { code: '02201', name: '2º Juzgado de Letras de Calama' },
    { code: '02201', name: '3º Juzgado de Letras de Calama' },
    { code: '02101', name: '1º Juzgado de Letras Civil de Antofagasta' },
    { code: '02101', name: '2º Juzgado de Letras Civil de Antofagasta' },
    { code: '02101', name: '3º Juzgado de Letras Civil de Antofagasta' },
    { code: '02101', name: '4 ° Juzgado de Letras Civil de Antofagasta' },
    { code: '02102', name: 'Juzgado de Letras y Garantía Mejillones' },
    { code: '03201', name: 'Juzgado de Letras y Gar. de Chañaral' },
    { code: '03202', name: 'Juzgado de Letras de Diego de Almagro' },
    { code: '03101', name: '1º Juzgado de Letras de Copiapó' },
    { code: '03101', name: '2º Juzgado de Letras de Copiapó' },
    { code: '03101', name: '3º Juzgado de Letras de Copiapó' },
    { code: '03303', name: 'Juzgado de Letras y Gar.de Freirina' },
    { code: '03101', name: '4º Juzgado de Letras de Copiapó' },
    { code: '03301', name: '1º Juzgado de Letras de Vallenar' },
    { code: '03301', name: '2º Juzgado de Letras de Vallenar' },
    { code: '03102', name: 'Juzgado de Letras y Gar.de Caldera' },
    { code: '04101', name: '1º Juzgado de Letras de la Serena' },
    { code: '04101', name: '2º Juzgado de Letras de la Serena' },
    { code: '04101', name: '3º Juzgado de Letras de la Serena' },
    { code: '04102', name: '1º Juzgado de Letras de Coquimbo' },
    { code: '04102', name: '2º Juzgado de Letras de Coquimbo' },
    { code: '04102', name: '3º Juzgado de Letras de Coquimbo' },
    { code: '04106', name: 'Juzgado de Letras de Vicuña' },
    { code: '04301', name: 'Juzgado de letras y garantía de Andacollo' },
    { code: '04301', name: '1º Juzgado de Letras de Ovalle' },
    { code: '04301', name: '2º Juzgado de Letras de Ovalle' },
    { code: '04301', name: '3º Juzgado de Letras de Ovalle' },
    { code: '04302', name: 'Juzgado de Letras y Gar.de Combarbalá' },
    { code: '04201', name: 'Juzgado de Letras de Illapel' },
    { code: '04203', name: 'Juzgado de Letras y Gar. de los Vilos' },
    { code: '05101', name: '1º Juzgado Civil de Valparaíso' },
    { code: '05101', name: '2º Juzgado Civil de Valparaíso' },
    { code: '05101', name: '3º Juzgado Civil de Valparaíso' },
    { code: '05101', name: '4º Juzgado Civil de Valparaíso' },
    { code: '05101', name: '5º Juzgado Civil de Valparaíso' },
    { code: '05109', name: '1º Juzgado Civil de Viña del Mar' },
    { code: '05109', name: '2º Juzgado Civil de Viña del Mar' },
    { code: '05109', name: '3º Juzgado Civil de Viña del Mar' },
    { code: '05804', name: 'Juzgado de Letras de Villa Alemana' },
    { code: '05102', name: 'Juzgado de Letras de Casablanca' },
    { code: '05401', name: 'Juzgado de Letras de La Ligua' },
    { code: '05404', name: 'Juzgado de Letras y Gar. de Petorca' },
    { code: '05701', name: '1º Juzgado de Letras de San Felipe Ex 2º' },
    { code: '05701', name: '1º Juzgado de Letras de San Felipe' },
    { code: '05705', name: 'Juzgado de Letras y Gar.de Putaendo' },
    { code: '05501', name: '1º Juzgado de Letras de Quillota' },
    { code: '05501', name: '2º Juzgado de Letras de Quillota' },
    { code: '05802', name: 'Juzgado de Letras de Limache' },
    { code: '05601', name: '1º Juzgado de Letras de San Antonio' },
    { code: '05601', name: '2º Juzgado de Letras de San Antonio' },
    { code: '05201', name: 'Juzgado de Letras y Gar. de Isla de Pascua' },
    { code: '05107', name: 'Juzgado de Letras y Gar.de Quintero' },
    { code: '06101', name: '1º Juzgado Civil de Rancagua' },
    { code: '06101', name: '2º Juzgado Civil de Rancagua' },
    { code: '06115', name: '1º Juzgado de Letras de Rengo' },
    { code: '06112', name: '1º Juzgado de Letras y Gar.de Peumo' },
    { code: '06301', name: '1º Juzgado de Letras de San Fernando' },
    { code: '06301', name: '2º Juzgado de Letras de San Fernando' },
    { code: '06310', name: '1º Juzgado De Letras De Santa Cruz Ex 2°' },
    { code: '06201', name: 'Juzgado de Letras y Gar.de Pichilemu' },
    { code: '06203', name: 'Juzgado de Letras y Gar.de Litueche' },
    { code: '06307', name: 'Juzgado de Letras y Gar.de Peralillo' },
    { code: '07101', name: '1º Juzgado de Letras de Talca' },
    { code: '07101', name: '2º Juzgado de Letras de Talca' },
    { code: '07101', name: '3º Juzgado de Letras de Talca' },
    { code: '07101', name: '4º Juzgado de Letras de Talca' },
    { code: '07102', name: 'Juzgado de Letras de Constitución' },
    { code: '07103', name: 'Juzgado De Letras Y Gar. de Curepto' },
    { code: '07301', name: '1º Juzgado de Letras de Curicó' },
    { code: '07301', name: '2º Juzgado de Letras de Curicó' },
    { code: '07301', name: '2º Juzgado de Letras de Curicó Ex 3°' },
    { code: '07303', name: 'Juzgado De Letras Y Gar. de Licantén' },
    { code: '07304', name: 'Juzgado de Letras de Molina' },
    { code: '07401', name: '1º Juzgado de Letras de Linares' },
    { code: '07401', name: '2º Juzgado de Letras de Linares' },
    { code: '07406', name: 'Juzgado de Letras de San Javier' },
    { code: '07201', name: 'Juzgado de Letras de Cauquenes' },
    { code: '07404', name: 'Juzgado de Letras y Gar. de Chanco' },
    { code: '07404', name: 'Juzgado de Letras de Parral' },
    { code: '08401', name: '1º Juzgado Civil de Chillán' },
    { code: '08401', name: '2º Juzgado Civil de Chillán' },
    { code: '08416', name: '1º Juzgado de Letras de San Carlos' },
    { code: '08421', name: 'Juzgado de Letras de Yungay' },
    { code: '08402', name: 'Juzgado de Letras y Gar. de Bulnes' },
    { code: '08404', name: 'Juzgado de Letras y Gar.de Coelemu' },
    { code: '08414', name: 'Juzgado de Letras y Gar.de Quirihue' },
    { code: '08301', name: '1º Juzgado de Letras de Los Angeles' },
    { code: '08301', name: '2° Juzgado de Letras de Los Angeles ex 3°' },
    { code: '08301', name: '2º Juzgado de Letras de Los Angeles' },
    { code: '08306', name: 'Juzgado de Letras y Gar.de Nacimiento' },
    { code: '08304', name: 'Juzgado de Letras y Gar.de Laja' },
    { code: '08313', name: 'Juzgado de Letras y Gar.de Yumbel' },
    { code: '08101', name: '1º Juzgado Civil de Concepción' },
    { code: '08101', name: '2º Juzgado Civil de Concepción' },
    { code: '08101', name: '3º Juzgado Civil de Concepción' },
    { code: '08110', name: '1º Juzgado Civil de Talcahuano' },
    { code: '08110', name: '2º Juzgado Civil de Talcahuano' },
    { code: '08111', name: 'Juzgado de Letras de Tomé' },
    { code: '08104', name: 'Juzgado de Letras y Gar.de Florida' },
    { code: '08109', name: 'Juzgado de Letras y Gar.de Santa Juana' },
    { code: '08106', name: 'Juzgado de Letras y Gar. de Lota' },
    { code: '08102', name: '1º Juzgado de Letras de Coronel' },
    { code: '08102', name: '2º Juzgado de Letras de Coronel' },
    { code: '08201', name: 'Juzgado de Letras y Gar.de Lebu' },
    { code: '08202', name: 'Juzgado de Letras de Arauco' },
    { code: '08205', name: 'Juzgado de Letras y Gar.de Curanilahue' },
    { code: '08203', name: 'Juzgado de Letras de Cañete' },
    { code: '08311', name: 'Juzgado de Letras y Gar. Santa Bárbara' },
    { code: '08303', name: 'Juzgado de Letras y Gar.de Cabrero' },
    { code: '09101', name: '1º Juzgado Civil de Temuco' },
    { code: '09101', name: '2º Juzgado Civil de Temuco' },
    { code: '09201', name: 'Juzgado de Letras de Angol' },
    { code: '09202', name: 'Juzgado de Letras y Gar.de Collipulli' },
    { code: '09210', name: 'Juzgado de Letras y Gar.de Traiguén' },
    { code: '09211', name: 'Juzgado de Letras de Victoria' },
    { code: '09109', name: 'Juzgado de Letras Loncoche' },
    { code: '09120', name: 'Juzgado de Letras de Villarrica' },
    { code: '09111', name: 'Juzgado de Letras de Nueva Imperial' },
    { code: '09115', name: 'Juzgado de Letras y Gar.de Pucón' },
    { code: '09108', name: 'Juzgado de Letras de Lautaro' },
    { code: '09102', name: 'Juzgado de Letras y Gar.de Carahue' },
    { code: '09101', name: '3º Juzgado Civil de Temuco' },
    { code: '14101', name: '1º Juzgado Civil de Valdivia' },
    { code: '14101', name: '2º Juzgado Civil de Valdivia' },
    { code: '14106', name: 'Juzgado de Letras de Mariquina' },
    { code: '14107', name: 'Juzgado de Letras y Gar.de Paillaco' },
    { code: '14108', name: 'Juzgado de Letras y Gar. de Panguipulli' },
    { code: '14201', name: 'Juzgado de Letras y Gar.de la Unión' },
    { code: '14204', name: 'Juzgado de Letras y Gar.de Río Bueno' },
    { code: '10301', name: '1º Juzgado de Letras de Osorno' },
    { code: '10301', name: '2º Juzgado de Letras de Osorno' },
    { code: '10101', name: '1º Juzgado Civil de Puerto Montt' },
    { code: '10101', name: '2º Juzgado Civil de Puerto Montt' },
    { code: '10109', name: 'Juzgado de Letras de Puerto Varas' },
    { code: '10102', name: 'Juzgado de Letras y Gar.de Calbuco' },
    { code: '10201', name: 'Juzgado de Letras de Castro' },
    { code: '10202', name: 'Juzgado de Letras de Ancud' },
    { code: '10401', name: 'Juzgado de Letras y Gar. de Chaitén' },
    { code: '10106', name: 'Juzgado de Letras y Gar. de Los Muermos' },
    { code: '10208', name: 'Juzgado de Letras y Gar. de Quellón' },
    { code: '11401', name: 'Juzgado de Letras y Gar.de Chile Chico' },
    { code: '11301', name: 'Juzgado de Letras y Gar.de Cochrane' },
    { code: '12101', name: '1º Juzgado de Letras de Punta Arenas' },
    { code: '12101', name: '2º Juzgado de Letras de Punta Arenas' },
    { code: '12101', name: '3º Juzgado de Letras de Punta Arenas' },
    { code: '12301', name: 'Juzgado de Letras y Gar.de Porvenir' },
    { code: '13101', name: '1º Juzgado Civil de Santiago' },
    { code: '13101', name: '2º Juzgado Civil de Santiago' },
    { code: '13101', name: '3º Juzgado Civil de Santiago' },
    { code: '13101', name: '4º Juzgado Civil de Santiago' },
    { code: '13101', name: '5º Juzgado Civil de Santiago' },
    { code: '13101', name: '6º Juzgado Civil de Santiago' },
    { code: '13101', name: '7º Juzgado Civil de Santiago' },
    { code: '13101', name: '8º Juzgado Civil de Santiago' },
    { code: '13101', name: '9º Juzgado Civil de Santiago' },
    { code: '13101', name: '10º Juzgado Civil de Santiago' },
    { code: '13101', name: '11º Juzgado Civil de Santiago' },
    { code: '13101', name: '12º Juzgado Civil de Santiago' },
    { code: '13101', name: '13º Juzgado Civil de Santiago' },
    { code: '13101', name: '14º Juzgado Civil de Santiago' },
    { code: '13101', name: '15º Juzgado Civil de Santiago' },
    { code: '13101', name: '16º Juzgado Civil de Santiago' },
    { code: '13101', name: '17º Juzgado Civil de Santiago' },
    { code: '13101', name: '18º Juzgado Civil de Santiago' },
    { code: '13101', name: '19º Juzgado Civil de Santiago' },
    { code: '13101', name: '20º Juzgado Civil de Santiago' },
    { code: '13101', name: '21º Juzgado Civil de Santiago' },
    { code: '13101', name: '22º Juzgado Civil de Santiago' },
    { code: '13101', name: '23º Juzgado Civil de Santiago' },
    { code: '13101', name: '24º Juzgado Civil de Santiago' },
    { code: '13101', name: '25º Juzgado Civil de Santiago' },
    { code: '13101', name: '26º Juzgado Civil de Santiago' },
    { code: '13101', name: '27º Juzgado Civil de Santiago' },
    { code: '13101', name: '28º Juzgado Civil de Santiago' },
    { code: '13101', name: '29º Juzgado Civil de Santiago' },
    { code: '13101', name: '30º Juzgado Civil de Santiago' },
    { code: '13301', name: 'Juzgado de Letras de Colina' },
    { code: '13130', name: '1º Juzgado Civil de San Miguel' },
    { code: '13130', name: '2º Juzgado Civil de San Miguel' },
    { code: '13130', name: '3º Juzgado Civil de San Miguel' },
    { code: '13130', name: '4º Juzgado Civil de San Miguel' },
    { code: '13201', name: '1º Juzgado Civil de Puente Alto' },
    { code: '13601', name: '1º Juzgado De Letras De Talagante' },
    { code: '13601', name: '2º Juzgado De Letras De Talagante' },
    { code: '13501', name: '1º Juzgado de Letras de Melipilla' },
    { code: '13402', name: '1º Juzgado de Letras de Buin' },
    { code: '13402', name: '2º Juzgado de Letras de Buin' },
    { code: '13605', name: 'Juzgado de Letras de Peñaflor' },
    { code: '13401', name: '1º Juzgado de Letras de San Bernardo' },
    { code: '13401', name: '1º Juzgado de Letras de San Bernardo Ex 3°' },
    { code: '13401', name: '2º Juzgado de Letras de San Bernardo' },
    { code: '13401', name: '2º Juzgado de Letras de San Bernardo Ex 3°' },
  ],
};
