# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    container_name: regions-db
    build:
      context: .
      dockerfile: pgDockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${EXTERNAL_POSTGRES_PORT}:${POSTGRES_PORT}'

  api:
    container_name: regions-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/${POSTGRES_HOST}/${POSTGRES_PORT}; do sleep 1; done; ${SCRIPT_FILE}'
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DB_DIALECT: ${DB_DIALECT}
      DEFAULT_PORT: ${DEFAULT_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '${EXTERNAL_API_PORT}:${DEFAULT_PORT}'
