#%RAML 1.0 DataType
description: |
    Regions and Communs supports OAuth 2.0 for authenticating all API requests.
  type: OAuth 2.0
  describedBy:
    headers:
      Authorization:
        description: |
            Used to send a valid OAuth 2 access token. Do not use
            with the "access_token" query string parameter.
        type: string
settings:
authorizationGrants: [ client_credentials ]